name: PR Docker Build

on:
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - 'src/**'
            - '!src/tests/**'
            - 'Dockerfile*'
            - '.dockerignore'
            - 'package*.json'
            - '!**.md'

jobs:
    docker-build:
        name: ğŸ³ Docker Build
        runs-on: ubuntu-latest
        needs: [build, unit-test, e2e-test]
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: false
                  load: true
                  tags: ${{ github.repository }}:pr-${{ github.event.pull_request.number }}

    e2e-test:
        name: ğŸ¤– E2E Bot Tests
        uses: ./.github/workflows/pr-e2e-test.yml

    unit-test:
        name: ğŸ§ª Unit Tests
        uses: ./.github/workflows/pr-unit-test.yml

    build:
        name: ğŸ”¨ Build
        uses: ./.github/workflows/pr-build.yml
